services:
  - type: web
    name: smgrowai-web
    runtime: node
    plan: free
    region: oregon
    autoDeploy: true
    buildCommand: npm ci && npx prisma generate && npx prisma db push --accept-data-loss && npm run build
    startCommand: npm start
    envVars:
    - key: NODE_VERSION
      value: 20
    - key: NODE_ENV
      value: production
    - key: NEXT_PUBLIC_NODE_ENV
      value: production
    - key: DATABASE_URL
      fromDatabase:
        name: smgrowai-db
        property: connectionString
    - key: AUTH_SECRET
      generateValue: true
    - key: NEXTAUTH_URL
      fromService:
        type: web
        name: smgrowai-web
        property: host
    - key: NEXT_PUBLIC_APP_URL
      fromService:
        type: web
        name: smgrowai-web
        property: host

databases:
  - name: smgrowai-db
    databaseName: smgrowai
    user: smgrowai
    plan: free
